- hosts: server
  tasks:
   - name: install python centos
     yum:
        name: python-docker
        state: present
     when:
        - ansible_distribution == "CentOS"
   - name: install python ubuntu
     apt:
        name: python-docker
        state: present
     when:
        - ansible_distribution == "Ubuntu"   
   - name: create container
     docker_container:
        name: container_by_jenkins
        image: adiyang/apache-ubuntu:latest
        state: started
        published_ports: 
        - 9000:80
        recreate: yes
        interactive: yes
        detach: yes
